### ISSUE TITLE
CloudConvert API Version?

### ISSUE THREAD

**Issue by teichsta** [bnomei/kirby3-cloudconvert#8]
Hi,

which API Version of CloudConvert did you implement? As CC is shutting down der v1 version beginning next year it would be great to see v2 implemented. Unfortunately v2 API seems to be much more complex.

Thanks in advance,

Thomas E.-E.

**Comment by bnomei** [comment]
i am using the official php lib v2. i will see if i can upgrad to v3.

but i dont know which api version that is internally.

https://github.com/cloudconvert/cloudconvert-php

**Comment by bnomei** [comment]
it uses v2 internally
> This is the official PHP SDK for the [CloudConvert](https://cloudconvert.com/api/v2) API v2.
